version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables: 
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per product_id found in each orders_id.
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)" 
          - not_null:
              column_name: "(orders_id || '_' || pdt_id)"
        freshness: 
          warn_after:
            {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
      - name: product
        identifier: raw_gz_product
        tests:
          - unique:
              column_name: products_id
          - not_null:
              column_name: products_id        
      - name: ship
        identifier: raw_gz_ship
        tests:
          - unique:
              column_name: orders_id
          - not_null:
              column_name: orders_id
           
